[font]
size = 12.0

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = [
  # uncomment the flavour you want below:
  # "catppuccin-mocha.toml"
  # "catppuccin-macchiato.toml"
  # "catppuccin-frappe.toml"
  # "tokyo-night.toml"
  # "tokyo-night-storm.toml"
  # "rose-pine.toml"
  # "rose-pine-moon.toml"
  "nord.toml"
]
