alias seba='source .env/bin/activate'
alias sa='source .env/bin/activate'
alias de='deactivate'
alias bt='bluetoothctl'
alias batt='upower -i `upower -e | grep 'BAT'`'
alias o='xdg-open'
alias tre='tree -L 4'
alias vim=nvim
alias v=nvim
